branches:
  only:
    - master
    - dev
os:
  - linux
language: node_js
node_js:
  - 12
addons:
  chrome: stable
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run test:cover
  - npm install coveralls
  - cat ./coverage/lcov.info | coveralls

before_deploy:
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(node -p "require('./package.json').version")-$(date +'%Y.%m.%d')-$(git log --format=%h -1)}
  - echo ${TRAVIS_TAG}
  - "if [[ ${TAGGED} != 1 ]]; then git tag ${TRAVIS_TAG} && export TAGGED=1; fi"
  - "if [[ ! -e lib ]]; then npm run build && export PACKAGE=$(npm pack --silent); fi"
deploy:
  - provider: releases
    skip_cleanup: true
    file: $PACKAGE
    api_key:
      secure: ddcX6LWvpcOjF8aiZgTN6QSmN8SIJidSC7K2MO34f1YwL4JSbFSl77QczhhLQt5N/Iplu3cFfCXuxBeDicxROv3LDNWrJTG94bNClO8MR1fyBxftCuFlVSfOLllpGhkkQ4LcBFdZjv6leGJuTcPWRds1Fa2xN7aJMxmVwoCXirkPxtHrMZbiCTyVh8ODquMcdtLJV8+KRMO+t+c6JNWoSK8a26sKY71KI31kj4Ffb2ape3aZ2fLJCpONMWktPJCrRuvUApGTzthVmYa/DcRbkAVna3XGMUKmkTD6DdT4YXnwgV+YLe4plCbwqqE7lGTwpIg7CzKSKUlAX9JtKtyNHGAfG8/GK4RqLRpRsFDw+kNmXuwrhrHZHeomCnf/ZpLq2ihK1GGpGyV5uVoLajoizBAlD+/d0vWYjNj5A0sAj8953/kevl/Kp+tgkE+pLOcjd9h+PzYTQVfqCPH0QPK0KgGH1w66ZCrHCyw1aaRF788MyDRNfKxGF+T6H37o6fp96lkVrq+qkTXZnKd8af9y0T4jxEfWoWhFHGj1G/MXkfb1Yeg2A3AM51o0JB0m9X2neEle7GE6mtdS34eX8+BbGbfFeZFam/Sut4+oosNy/WBWrNyMZXKDz1tTPVF44mhUAu9gglwbQixknAvpB+KYBtsD7/bzinGd8cCtxb+m7o0=
    on:
      repo: eidng8/xml-patch
      branch: master
      #tags: true
      condition: ${TRAVIS_EVENT_TYPE} == push
  - provider: npm
    skip_cleanup: true
    email: cheung.jackey@gmail.com
    api_key:
      secure: IYXtCAhIbZ0UT9howhUf3BX24E0gy7koOGLGzyLZnqnoVmwerNfpXIxeWG8COYg+SRpIIPXt5QhIomtQOB/VVQMCKz/zj4QMpCZNDH4YTNvIYrxpyoalrTB7WdZ+TisCZjbiuvFdicRLsbQOGU6pc5m0CRf5/tBfe4MJQfncvOv/3QTFTSHvPYqjd5T1daASaMxFGlVvXna58QzaRdyQA0IPFwyYA1QJdAteGPYlxMNIsGHBoSInilUltaQhjn9RzzjjK9gLKHFKH9aMckhkHwbDpH/V+yDNy/JLtvF9X4ZPUW8TxZH4bsRVAqp430XR+3CWZQRL/ReApKgqDmVqnQBMMwrUPlKC1oIDe3iiHnAHrcILzaFPet20vtntZyaEfXpOHYx+Tnj2fQElFM3TgYXfjcehL09p1IriBwf8MNGVYQsdsdat8uqUhvKK/9LJ8EMm6XAN0gXo0EQ43IvzLsAwbbZKubh9y2Jp1ntRjXzDeHthjNt81/+ODqQRg3b/F9AosJS827dxy79NaOK2+cR2dEHHcByp7UUEPsA2kGmfGfQKi/Tp7pznT2OQ0NYmmA0+Xy1jdmA/OHXm+K4Law+//Ze3+XLSVmHoB/JcEyyo6p7t+Bg1rBs8aopGMB1XpMdNQ7jdki7OSq5OAxty4SwzxQym076LxutensI+7DE=
    on:
      repo: eidng8/xml-patch
      branch: master
      condition: ${TRAVIS_EVENT_TYPE} == push
      #tags: true
